<h3 class="pad-10">Login</h3>
<div class="light-container mrg-10-b">
    <table cellspacing="0" cellpadding="0">
        <tr>
            <td valign="top">
                <div class="inline-form-container">
                    <form action="<?php echo $this->url(); ?>" method="post">
                        <ul>
                            <li>
                                <label>E-mail:</label>
                                <?php echo $this->formLogin->getItem('username'); ?>
                            </li>
                            <li>
                                <label>Password:</label>
                                <?php echo $this->formLogin->getItem('password'); ?>
                            </li>
                            <li>
                                <input type="submit" name="" value="login" />
                            </li>
                        </ul>
                    </form>
                </div>
            </td>
            <td valign="top" class="pad-10-l">
                <h2>Not a member yet?</h2>
                <h3>Join Cams now and get immediate access to the hottest models LIVE!</h3>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur
            </td>
        </tr>
    </table>
</div>